sudo: required
language: android

after_failure: "cat $TRAVIS_BUILD_DIR/lint-results-debug.xml"

jdk:
  - oraclejdk8

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-26.0.1
    - android-26

before_install:
  - echo yes | sudo sdkmanager --licenses
  - chmod +x gradlew

script:
  - ./gradlew build
